<?php
namespace sumaysigue\modelo;

require "vendor/autoload.php";

use sumaysigue\modelo\Saludo;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-22 at 12:45:07.
 */
class SaludoTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Saludo
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Saludo();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }


    /**
     * @dataProvider proveedorTestFormatSaludo
     */
    public function testFormatSaludo($saludo,$saludoEsperado) {
        $this->object->setSaludo($saludo);
        $saludoObtenido = $this->object->formatSaludo();
        $this->assertEquals($saludoEsperado,$saludoObtenido);
    }
    
    public function proveedorTestFormatSaludo(){
        return [
          "Saludo 1" => ["Hola","El mensaje es: Hola"],
          "Saludo 2" => ["Adios","El mensaje es: Adios"]
        ];
    }
}
